### ISSUE TITLE
Opt-in to hacktoberfest

### ISSUE THREAD

**Issue by yoursunny** [named-data/YaNFD#11]
I'd like to contribute to this repository as part of Hacktoberfest. One feature I'd like to contribute is a WebSocket server, which enables web applications to connect to YaNFD just like how they work with NFD reference implementation.
In order for the Pull Requests to count toward my Hacktoberfest contributions, it is necessary for the maintainer to add `hacktoberfest` as a repository topic. Can you do that?
https://hacktoberfest.digitalocean.com/resources/maintainers

**Comment by zjkmxy** [comment]
Done. Thanks for your interest.

**Comment by yoursunny** [comment]
Thanks @zjkmxy!
I'll get things started this weekend.
