### ISSUE TITLE
Most of the nfdc commands are not supported

### ISSUE THREAD

**Issue by sudocn** [named-data/YaNFD#23]
I use the newest YaNFD compiled from Github source, and nfdc (v 0.7.1) also compile from Github source 

most of the nfdc mgmt cmds fails with YaNFD, such as 'nfdc face', 'nfdc route' etc.

Logs here
<pre>
root@75b4fe29f353:/generated# yanfd -version
YaNFD: Yet another NDN Forwarding Daemon
Version 0.0.1-cbcb2d1
Copyright (C) 2020-2021 Eric Newberry
Released under the terms of the MIT License
root@75b4fe29f353:/generated# nfdc --version
0.7.1
root@75b4fe29f353:/generated# nfdc face
Error 500 when querying face: Data Name has no segment number
root@75b4fe29f353:/generated# nfdc route
Error 500 when fetching RIB dataset: Data Name has no segment number
root@75b4fe29f353:/generated# nfdc status
Error while collecting status report (500).
General NFD status:
                version=
              startTime=19700101T000000
            currentTime=19700101T000000
                 uptime=0 seconds
       nNameTreeEntries=0
            nFibEntries=0
            nPitEntries=0
   nMeasurementsEntries=0
             nCsEntries=0
           nInInterests=0
          nOutInterests=0
                nInData=0
               nOutData=0
               nInNacks=0
              nOutNacks=0
    nSatisfiedInterests=0
  nUnsatisfiedInterests=0
</pre>

**Comment by zjkmxy** [comment]
I think this is related to [naming convention 3](https://named-data.net/publications/techreports/ndn-tr-22-3-ndn-memo-naming-conventions). Current `master` branch of YaNFD has already updated to this new naming convention, but the `nfdc` you were using has not.
Could you please install `ndn-cxx` and `NFD` from GitHub and try again?

**Comment by sudocn** [comment]
Confirmed.

nfdc complied from master branch can interact /w YaNFD correctly.
