### ISSUE TITLE
Reproducible build

### ISSUE THREAD

**Issue by yoursunny** [named-data/YaNFD#4]
@Pesa [said](https://github.com/usnistgov/ndn-dpdk/issues/2) the build process should be [reproducible](https://reproducible-builds.org/).

The first problem I've noticed is that `Makefile` embeds a timestamp when linking `cmd/yanfd` package. We should [get rid of the timestamp](https://reproducible-builds.org/docs/timestamps/). There may be other sources of non-reproducibility in the build system.

**Comment by eric135** [comment]
I removed the build time from the executable.
