### ISSUE TITLE
Installation via pkg.go.dev

### ISSUE THREAD

**Issue by justincpresley** [named-data/YaNFD#47]
## Version Discrepancy

The [latest version of yanfd according to pkg.go.dev](https://pkg.go.dev/github.com/named-data/YaNFD/cmd/yanfd) is `v1.1.1` which was published on May 9, 2022. In contrast, the [github (source) of yanfd](https://github.com/named-data/YaNFD/releases) states that the latest version is `v1.1.0` published on April 21, 2022.

I believe this issue originated when moving the repository of **yanfd** from the account of @zjkmxy to the organization of @named-data. My justification for this is that [the fork of zjkmxy has a tag called v1.1.1](https://github.com/zjkmxy/YaNFD/tags). I am not confidence how this issue can be handled. Releasing a version past v1.1.1 likely will not resolve the issue.

However, this is arguably an critical issue as users will be lead to install out-of-dated software thinking it is the updated version reflected on Github (where they are reading the README to install).

## Installation Needs

When installing **yanfd** on a Ubuntu 20.04, Linux system [according to the README](https://github.com/named-data/YaNFD/blob/master/README.md). there were a series of errors that were resolved by installing extra dependencies not stated in the README. The following were the list of packages that I needed to install via apt before running YaNFD:
* `libpcap-dev`
* `gcc/g++`

Making this clear will ease installation for beginners.

## Needed Released

There has been [several changes to YaNFD](https://github.com/named-data/YaNFD/compare/v1.1.0...HEAD) that I believe warrant a upcoming release.

**Comment by Pesa** [comment]
> The [latest version of yanfd according to pkg.go.dev](https://pkg.go.dev/github.com/named-data/YaNFD/cmd/yanfd) is `v1.1.1` which was published on May 9, 2022. In contrast, the [github (source) of yanfd](https://github.com/named-data/YaNFD/releases) states that the latest version is `v1.1.0` published on April 21, 2022.

A `v1.1.1` tag [does exist](https://github.com/named-data/YaNFD/releases/tag/v1.1.1) in this repo, but there is no corresponding "release" for it. As you know, "release" is a github-specific concept, and unfortunately the github UI will prefer showing the latest "release" on the main page of the repo even if it's outdated, i.e., even if a newer tag exists. Yes, it is confusing.

**Comment by zjkmxy** [comment]
Thank you for your comments.
Version Discrepancy: I have already released v1.1.1. As stated by Davide, the tag exists, just not released because I added this tag through git push instead of github UI.
Installation Needs: Will handle it.
Needed Released: Will handle it.

**Comment by zjkmxy** [comment]
I did the changes you requested. But I don't have time to work on the Windows Store release for now. Let me leave this issue open.

**Comment by justincpresley** [comment]
Just to note, there is a misspelling of `libpcap` in the Prerequisites ( `libpacp` ).

**Comment by zjkmxy** [comment]
I have uploaded v1.2.0.0 to Windows Store and it is in certification progress. I think it is time to close this issue if there is no other problems.
