### ISSUE TITLE
Some dependencies of YaNFD are not being maintained

### ISSUE THREAD

**Issue by zjkmxy** [named-data/YaNFD#48]
- ~~[github.com/gorilla/websocket](https://github.com/gorilla/websocket): is not being maintained any more. See https://github.com/gorilla#gorilla-toolkit~~
- ~~[github.com/google/gopacket](https://github.com/google/gopacket): has some commits last year, but depends on out-of-dated `golang.org/x/net` and `golang.org/x/sys`. These versions have several security bugs reported on CVE but the maintainers seem to have no interest updating the dependencies.~~
- ~~[github.com/zjkmxy/stealthpool](https://github.com/zjkmxy/stealthpool): has already been abandoned by the original author so I have to maintain a separate fork to make it work.~~
- [github.com/apex/log](github.com/apex/log): the author became inactive for a long time but the package seems to work well for our usage.

Don't know when these packages will stop working and we have to find alternatives, but they may happen in future. This issue is opened to mark this potential problem. No action needs to be done now.

**Comment by yoursunny** [comment]
GoPacket author left Google LLC and cannot update the original repository.
They are maintaining a fork instead:
https://github.com/gopacket/gopacket
