### ISSUE TITLE
Cant Fetch form Github

### ISSUE THREAD

**Issue by mahesamf** [named-data/YaNFD#61]
There is an error like this. Previously this morning i successed to fetch that but because there is same issue like this when i want to do "make" in YaNFD.
go install github.com/named-data/YaNFD/cmd/yanfd@latest
go: github.com/named-data/YaNFD/cmd/yanfd@latest: module github.com/named-data/YaNFD/cmd/yanfd: Get "https://proxy.golang.org/github.com/named-data/%21ya%21n%21f%21d/cmd/yanfd/@v/list": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-10-15T13:46:05+07:00 is after 2023-03-19T23:59:59Z
Can someone help me solve this? Thx

**Comment by zjkmxy** [comment]
Thank you for reporting this. But this error does not look like an error in YaNFD, but rather an issue with `proxy.golang.org`.
Let me see if other people have the same issue.

**Comment by mahesamf** [comment]
Thank you, sir, I hope that the problem of this issue will be resolved soon for us

**Comment by mahesamf** [comment]
The issue is clear, Thank you mr.zjkmxy
The issue is come possibly from my WiFi because i change into hotspot from my phone and it is work.

**Comment by zjkmxy** [comment]
Great.
