### ISSUE TITLE
Switch configuration to YAML

### ISSUE THREAD

**Issue by pulsejet** [named-data/YaNFD#68]
I don't like TOML, it's annoying.

YAML is a superset of JSON => trivial to automate stuff e.g. in MiniNDN

@Pesa @zjkmxy @yoursunny any objections?

**Comment by zjkmxy** [comment]
I think it's good to use YAML.

**Comment by Pesa** [comment]
The typical criticism of YAML is that it's a very complex format and overkill for configuration data. Plenty of articles have been written on this topic, e.g. https://www.arp242.net/yaml-config.html

That said, I have no horse in this race.

> I don't like TOML, it's annoying.

I'm curious, what specifically do you find annoying?

> YAML is a superset of JSON => trivial to automate stuff e.g. in MiniNDN

In the case of minindn, python has built-in TOML support, so I don't see the issue. If you're talking about CLI manipulation à la `jq`, you can use `tomlq` or `dasel` for TOML.

**Comment by pulsejet** [comment]
Interesting read, thanks for linking the article. I'll agree that the format is too complex but I don't see how it hurts if you don't use the weird bits (and if you have good reason to, you needed the complexity then?)

> I'm curious, what specifically do you find annoying?

1. (Personal preference) Yaml syntax is more readable. Indented toml looks like a big flat document impossible to visually parse. But I'm likely biased here since I've spent the last year reading CI configuration.
2. (Related to 1) I'll assume any users of our software are also more familiar with Yaml.
3. Yaml tooling has the edge (maybe unfortunately). For instance, opening a Yaml config file in a fresh vs code instance will give you syntax highlighting, but not for Toml.
4. Yaml/Json have better schema validation support, AFAIK. Also right in the IDE.

> In the case of minindn, python has built-in TOML support

Referring to tomllib? It only supports parse, not write. I don't consider this a major issue though.

> can use tomlq or dasel for TOML

Good to know 👀

**Comment by zjkmxy** [comment]
> 1. (Personal preference) Yaml syntax is more readable. Indented toml looks like a big flat document impossible to visually parse. But I'm likely biased here since I've spent the last year reading CI configuration.
> 2. (Related to 1) I'll assume any users of our software are also more familiar with Yaml.

I think TOML is more like old INI files. People with lot of experience on old Windows API programming or hand-crafted systemd services may be more used to it.

**Comment by Pesa** [comment]
> > 1. (Personal preference) Yaml syntax is more readable. Indented toml looks like a big flat document impossible to visually parse. But I'm likely biased here since I've spent the last year reading CI configuration.
> > 2. (Related to 1) I'll assume any users of our software are also more familiar with Yaml.
> 
> I think TOML is more like old INI files. People with lot of experience on old Windows API programming or hand-crafted systemd services may be more used to it.

The entire Cargo ecosystem and modern Python packaging are based on TOML, so I guess you should add practically all Python and Rust developers to the list...

**Comment by pulsejet** [comment]
> The entire Cargo ecosystem and modern Python packaging are based on TOML, so I guess you should add practically all Python and Rust developers to the list...

But these are barely "config" files. At least not edited by hand very often.
