### ISSUE TITLE
faces/create refuses udp4://127.0.0.1:7001

### ISSUE THREAD

**Issue by yoursunny** [named-data/YaNFD#78]
It appears that YaNFD refuses to create a face with remote `udp4://127.0.0.1:7001` and returns a ControlResponse with statusCode=406.
In contrast, NFD 24.07-1-gee97f534 would accept such commands.

## YaNFD command line and relevant output

YaNFD revision d10c0a66bb7863e0e8fa2a74ce0c72ab9db4d9cd

```text
ubuntu@ndndev:~/YaNFD$ sudo ./yanfd -config yanfd.sample.yml 

  INFO[0015] [TCPListener, tcp4://127.0.0.1:6363] Accepting new TCP face tcp4://127.0.0.1:55718
  WARN[0015] [FaceMgmt] Cannot create unicast UDP face to non-unicast address udp4://127.0.0.1:7001
  INFO[0015] [FaceTable] Unregistered FaceID=7
```

## NDNts snippet and relevant output

https://github.com/yoursunny/NDNts/blob/60c652ba0c686211de2cdcf58ea3b18a3eced9a9/integ/nfdmgmt-interop/face-rib.ts#L16-L29

```text
ubuntu@ndndev:~/NDNts$ NDNTS_UPLINK=tcp://127.0.0.1:6363 corepack pnpm literate integ/nfdmgmt-interop/face-rib.ts

[faces/create]
node:internal/modules/run_main:122
    triggerUncaughtException(
    ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

406 !== 200

    at file:///home/ubuntu/NDNts/integ/nfdmgmt-interop/face-rib.ts:18:8
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 406,
  expected: 200,
  operator: 'strictEqual'
}

Node.js v22.11.0
 ELIFECYCLE  Command failed with exit code 1.
```

## Packet Trace

Relevant packets are in frame 10 and frame 11.
[1.pcapng.gz](https://github.com/user-attachments/files/18220146/1.pcapng.gz)

**Comment by pulsejet** [comment]
Thanks for reporting this
